#!/usr/bin/env bash

set -xe

if [ -n "$1" ]; then
  BUILD_DIR=$1
else
  echo "Build directory isn't provided"
  exit 1
fi

BUILDROOT_VER="${BUILDROOT_VER:-2015.05}"
BUILDROOT_URL="${BUILDROOT_URL:-http://buildroot.uclibc.org/downloads/buildroot-${BUILDROOT_VER}.tar.gz}"
KERNEL_VER="${KERNEL_VER:-3.19.0-20.20~14.04.1}"
GRUB_VER="${GRUB_VER:-2.02~beta2-36ubuntu8}"
ARCH="${ARCH:-x86_64}"
OUTPUT_DIR="${OUTPUT_DIR:-/opt/images}"

#prepare environment
cd "${BUILD_DIR}"
./bin/system-setup
apt-get install python grub-common git -y

# download and build buildroot
mkdir -p ../download
ln -snf ../download download
wget -P download "${BUILDROOT_URL}"
tar -xvf download/buildroot-"${BUILDROOT_VER}".tar.gz
ln -snf buildroot-"${BUILDROOT_VER}" buildroot
pushd buildroot
  QUILT_PATCHES=./../patches-buildroot quilt push -a
popd
make ARCH="${ARCH}" br-source
make ARCH="${ARCH}" OUT_D=/opt/images

#TODO: this code is incompatible with cirros src tags =<0.3.5,
# it works on cirros trunk, need to think about compatibility with tags
./bin/grab-kernels "${KERNEL_VER}" "${ARCH}"

# grab-grub-* scripts are available in trunk (after 0.3.5)
if [ -n "${GRAB_GRUB}" ]; then
  ./bin/grab-grub-efi "${GRUB_VER}" "${ARCH}"
  GRUB_TAR="download/grub-efi-${ARCH}.tar.gz"
fi

bundle_args=(-v --arch=${ARCH} ${OUTPUT_DIR}/rootfs.tar download/kernel-${ARCH}.deb ${GRUB_TAR} ${OUTPUT_DIR})

./bin/bundle "${bundle_args[@]}"
